improve threaddumping and added code to prevent JVM from getting out of memory on shutdown

diff --git a/etc/init.d/jira b/etc/init.d/jira
--- a/etc/init.d/jira
+++ b/etc/init.d/jira
@@ -155,6 +155,28 @@ function wait_to_end() {
             get_PID
 }
 
+function thread_dump() {
+  get_PID
+  count=5
+  delay=0.5
+
+  if which jstack >/dev/null ; then
+
+    echo "Taking ${count} thread dumps for PID=$PID with ${delay} seconds inbetween..."
+    while [ $count -gt 0 ]
+    do
+      DUMP="${ROOT_DIR}/../logs/threaddump.$PID.$(date +%H%M%S.%N).txt"
+      echo "---" >> ${DUMP}
+      jstack -l $PID >> ${DUMP}
+      sleep $delay
+      let count--
+      echo -n "."
+    done
+
+  else
+    echo "jstack not found, skipping thread dumping."
+  fi
+}
 
 function daemon_start() {
         # rotating the logs, so we get an empty set for each restart
@@ -184,14 +206,18 @@ function daemon_start() {
 
 function daemon_stop() {
     log_progress_msg " shutdown.sh "
-    "${ROOT_DIR}/shutdown.sh" 2>&1 >>${OUTPUT} || true
+    SHUTDOWN=1 "${ROOT_DIR}/shutdown.sh" || true
+    # 2>&1 >>${OUTPUT} || true
     wait_to_end
         if [ -n "$PID" ]; then
             log_progress_msg " forcing "
-            "${ROOT_DIR}/shutdown.sh" -force 2>&1 >>${OUTPUT} || true
+            thread_dump
+            SHUTDOWN=1 "${ROOT_DIR}/shutdown.sh" 20 -force  || true
+            # 2>&1 >>${OUTPUT}
             wait_to_end
             if [ -n "$PID" ]; then
                     log_progress_msg " killing $PID "
+                    thread_dump
                     kill -9 $PID
                     wait_to_end
             fi
